namespace Utility
{
    public enum PickupEnum
    {
        ENERGY,
        WATER,
        SEED,
        LAVANDULA_X,
        CUCURBITA_X,
        CORYLUS_X,
        SNOWHEAP,
        HAILTREE,
        MEDUSA_FLYTRAP,
        LION_FLOWER,
        FERE_MOSS,
        GEHENNA,
        WHITELION,
        GLACIPILA,
        IRONGIANT,
        CATNIP_2_0,
        PITFALL_GOURD,
        DRAGONBORN,
        LIFE_HERB,
        LIBRA_DE_FOCUS,
        PYROPHITE,
        HELLFLOWER,
        GHIDORAH,
        SACRED_LIFE
    }
}
